### PR TITLE
Dynamic authorities.

### PR DESCRIPTION
**Pull request by mateosilguero**
### Description of changes

This is necessary for android flavors and dynamic applicationId (applicationIdSuffix).
sources: 

https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/RNSharePathUtil.java#L32

https://github.com/react-native-community/react-native-share/blob/master/android/src/main/AndroidManifest.xml#L9

### I did Exploratory testing:
- [x] android
- [x] ios

### Can it be published to NPM?
- [ ] Breaking change
- [ ] Documentation is updated

### CODE REVIEW

**Comment by MadeinFrance** [comment]
Awesome, I was looking for this. Thank you for the help Mateo 🥇

**Comment by mateosilguero** [comment]
Hi ! sorry for bother, is this already available at npm ?

**Comment by MadeinFrance** [comment]
It's not clear for me.

Yesterday I published with `npm publish` (no errors)

If I do `npm view react-native-share-pdf` I got the following output:

```
react-native-share-pdf@0.0.6 | MIT | deps: none | versions: 5
React native share PDF base64
https://github.com/MadeinFrance/react-native-share-pdf#readme

dist
.tarball: https://pkgs.dev.azure.com/IngEurCDaaS01/_packaging/P01283-incoming-private/npm/registry/react-native-share-pdf/-/react-native-share-pdf-0.0.6.tgz
.shasum: 731be00ab28a5e907016aa4c559910d1d2a4f550

dist-tags:
latest: 0.0.6  

published 23 hours ago
```

I see the new version: `0.0.6` but not on the NPM website, why?

**Comment by mateosilguero** [comment]
i just do this:

```
npm view react-native-share-pdf

react-native-share-pdf@0.0.5 | MIT | deps: none | versions: 4
React native share PDF base64
https://github.com/MadeinFrance/react-native-share-pdf#readme

keywords: react-native base64 share pdf

dist
.tarball: https://registry.npmjs.org/react-native-share-pdf/-/react-native-share-pdf-0.0.5.tgz
.shasum: e3e76838c45c44fe6e75a34e1d863735c28a43b1
.integrity: sha512-7rldfmsMWvf++O7yE1LrO8hctMJtNhF2UBbI+3wBlUz9xmxGkse5p1hv2h2CKjjuTNEwpnsnEOdiuJR0QjVgKw==
.unpackedSize: 106.1 kB

maintainers:
- madeinfrance <maximegerbe@gmail.com>

dist-tags:
latest: 0.0.5  
```

**Comment by MadeinFrance** [comment]
[`0.0.6`](https://www.npmjs.com/package/react-native-share-pdf/v/0.0.6) is live 🎉

```
A new version of the package react-native-share-pdf (0.0.6) was published at 2020-09-23T20:21:43.629Z from
2a02:a210:2a84:c680:b866:ea39:8c99:5404. The shasum of this package was 731be00ab28a5e907016aa4c559910d1d2a4f550.
```

**Comment by mateosilguero** [comment]
Awesome ! Thanks a lot

**Pull request merged**
